using UnityEngine;
using System.Collections;

public class CutsceneTriggerSequence : MonoBehaviour
{
    public int[] cutsceneIndices;           // ğŸ”¥ Inspectorì—ì„œ ì„¤ì •
    private bool triggered = false;


    public AudioSource audiosource; // ì˜¤ë””ì˜¤ì¶”ê°€



    private IEnumerator DelayedAudioPlay(float delay)
    {
        yield return new WaitForSecondsRealtime(delay); // â³ ê²Œì„ ì •ì§€ ë¬´ì‹œí•˜ê³  ì‹œê°„ ì§€ì—°
        AudioPlay(); // ğŸµ ì˜¤ë””ì˜¤ ì¬ìƒ
    }

    void AudioPlay()
    {
        if (!audiosource.isPlaying)
            audiosource.Play();

    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (triggered || !other.CompareTag("Player")) return;
        triggered = true;

        var manager = FindFirstObjectByType<CutsceneManager>();
        if (manager != null)
        {
            manager.ShowCutsceneSequence(cutsceneIndices);
        }

        StartCoroutine(DelayedAudioPlay(2f));
    }
}
